name: like all videos in playlist

on:
  workflow_dispatch:
  schedule:
    # 毎月日本時間1日の24時に実行
    - cron: '0 15 1 * *'

jobs:
  like_all_videos_in_playlist:
    runs-on: ubuntu-latest
    # リポジトリのオーナーしか実行できないようにする
    if: github.triggering_actor == github.repository_owner
    # main という環境名を指定
    environment: main
    steps:
      # mainブランチの内容をコピー
      - name: Checkout main
        uses: actions/checkout@v4

      # Bunをインストール
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # 依存関係をインストール
      - name: Install dependencies
        # 開発用パッケージは不要
        # prepareコマンドを実行しない
        run: bun install --production --ignore-scripts

      # スクリプトを実行
      - name: Run script
        env:
          YOUTUBE_DATA_API_REFRESH_TOKEN: ${{ secrets.YOUTUBE_DATA_API_REFRESH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun run scripts/rate-all-videos-in-playlist.ts --no-save --rating like --ids ${{ vars.LIKE_ALL_VIDEOS_IN_PLAYLIST_TARGET_ID }}
